### ISSUE TITLE
Error when customer not found

### ISSUE THREAD

**Issue by pimhooghiemstra** [iautomation/Groove-PHP-Wrapper#1]
I am integrating your class in my application but currently running against the wall. It seems that the code breaks when you are trying to get a customer by email and there is no customer registered in Groove with this email. 

My code gives an error in the request function as shown in the screenshot below.

Am I doing something wrong or could this be a bug?

Would nice to hear from you!

![screen shot 2015-10-28 at 14 34 21](https://cloud.githubusercontent.com/assets/7228111/10789985/004e003a-7d81-11e5-96ba-a14f96d4f047.png)

**Comment by iautomation** [comment]
Hi there. I'm happy to know the class is useful to you.

This error is up to Groove, and I believe it's correct, however I did not initially build in exception handling. I've done that now, which you can see on lines 84 & 100. https://github.com/iautomation/Groove-PHP-Wrapper/blob/master/groove.class.php

Example usage, for your case:
```
$g = new groove('xxxxxxxxxxxxxxxxxxxxxx');
try {
	$customer = $g->getCustomer('test@test.com');
} catch(Exception $e){
	echo 'customer not found';
}
```

I no longer work for the employer that used Groove, so I cannot thoroughly test this, so let me know if this works for you, and/or you need any more changes.

**Comment by pimhooghiemstra** [comment]
Dear Joshua,

I am trying to make it work within a Laravel application. So when I use
your supplied code snippet it indeed throws the error. However, in this
particular case it is not the behavior I am looking for. Since I would like
to show the Groove information for the customer if found or do nothing
otherwise. Would that be possible by changing the thrown exception into
something else?

We will have a look tomorrow in more detail to find out if we can fix it
for our situation ourselves. Thanks for the swift reply though, very
grateful!

Cheers, Pim

2015-10-28 18:56 GMT+01:00 Joshua McKenzie <notifications@github.com>:

**Comment by pimhooghiemstra** [comment]
Everything works now, thanks for the change in the code!
